# Generated by Django 5.0.3 on 2024-04-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_history',
        ),
    ]
