# Generated by Django 5.0.3 on 2024-04-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_history',
            name='userID',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
        migrations.DeleteModel(
            name='tbl_history',
        ),
    ]
