# Generated by Django 5.0.3 on 2024-04-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_seller'),
        ('Seller', '0007_tbl_product_sellerid'),
        ('User', '0008_remove_tbl_history_userid_delete_tbl_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_status', models.IntegerField(default='0')),
                ('cart_quantity', models.IntegerField(max_length=11)),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_history', models.CharField(max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
